'use strict';

gloomhaven_tiles = [
{ url: "https://doc-10-70-docs.googleusercontent.com/docs/securesc/im5unkpff3i0lhvubamqcl7036l1j3ne/4nfjmhob7jj776mm6pjv6qm8g6v3nbih/1552694400000/03164054090578463837/09468333584433715445/1sovfuNsmMmwgGrJO7T96Xt5cetEX0TGf",
 cachename: "A1a-Man-Made Stone - U1.png",},
{ cachename: "A1b-Man-Made Wood - D1.png",},
{ cachename: "A2a-Man-Made Stone - U2.png",},
{ cachename: "A2b-Natural Stone - D.png",},
{ cachename: "A3a-Natural Stone - U.png",},
{ cachename: "A3b-Man-Made Stone - D1.png",},
{ cachename: "A4a-Earth - U1.png",},
{ cachename: "A4b-Man-Made Stone - D2.png",},
{ cachename: "B1a-Man-Made Wood - U1.png",},
{ cachename: "B1b-Earth - D.png",},
{ cachename: "B2a-Man-Made Wood - U2.png",},
{ cachename: "B2b-Man-Made Stone - D1.png",},
{ cachename: "B3a-Man-Made Wood - U3.png",},
{ cachename: "B3b-Man-Made Stone - D2.png",},
{ cachename: "B4a-Man-Made Wood - U4.png",},
{ cachename: "B4b-Natural Stone - D.png",},
{ cachename: "C1a-Man-Made Stone - U.png",},
{ cachename: "C1b-Man-Made Wood - D.png",},
{ cachename: "C2a-Earth - U.png",},
{ cachename: "C2b-Man Made Stone - D.png",},
{ cachename: "D1a-Man-Made Stone - U1.png",},
{ cachename: "D1b-Earth - D.png",},
{ cachename: "D2a-Man-Made Stone - U2.png",},
{ cachename: "D2b-Natural Stone - D.png",},
{ cachename: "E1a-Man-Made Stone.png",},
{ cachename: "E1b-Natural Stone.png",},
{ cachename: "F1a-Man-Made Stone.png",},
{ cachename: "F1b-Earth.png",},
{ cachename: "G1a-Earth - U1.png",},
{ cachename: "G1b-Man-Made Stone - D1.png",},
{ cachename: "G2a-Natural Stone - U1.png",},
{ cachename: "G2b-Man-Made Wood - D1.png",},
{ cachename: "H1a-Natural Stone - U1.png",},
{ cachename: "H1b-Man-Made Stone D1.png",},
{ cachename: "H2a-Natural Stone - U2.png",},
{ cachename: "H2b-Earth - D1.png",},
{ cachename: "H3a-Man-Made Wood U.png",},
{ cachename: "H3b-Man-Made Stone D2.png",},
{ cachename: "I1a-Man-Made Wood - U.png",},
{ cachename: "I1b-Man-Made Stone - D.png",},
{ cachename: "I2a-Natural Stone - U.png",},
{ cachename: "I2b-Man-Made Wood - D.png",},
{ cachename: "J1a-Man-Made Stone - U1.png",},
{ cachename: "J1b-Natural Stone - D1 (1).png",},
{ cachename: "J1b-Natural Stone - D1.png",},
{ cachename: "J2a-Man-Made Stone - U2.png",},
{ cachename: "J2b-Natural Stone - D2.png",},
{ cachename: "K1a-Man-Made Stone - U1.png",},
{ cachename: "K1b-Natural Stone - D1.png",},
{ cachename: "K2a-Natural Stone - U1.png",},
{ cachename: "K2b-Man-Made Stone - D1.png",},
{ cachename: "L1a-Man-Made Stone 1.png",},
{ cachename: "L1b-Earth 2.png",},
{ cachename: "L2a-Natural Stone 1.png",},
{ cachename: "L2b-Man-Made Stone 2.png",},
{ cachename: "L3a-Earth 1.png",},
{ cachename: "L3b-Natural Stone 2.png",},
{ cachename: "M1a-Man-Made Stone.png",},
{ cachename: "M1b-Earth.png",},
{ cachename: "N1a-Natural Stone - U.png",},
{ cachename: "N1b-Man-Made Stone - D.png",},
];

