start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1EqhZWQopveEBzEImqhiwaVWJuAxHvnh0"
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1sovfuNsmMmwgGrJO7T96Xt5cetEX0TGf"
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ywMGrOGtYgsIh2qkGaGywBuUp9q8ABKn
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1HvmzI4q7ajwr6A_a6f5nhJ94ajs1U59n
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1cAtagBDwyi6UEv5lPZ3oh0RJvfezZQ9W
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1hfKTfwCgJlsSiZv6Zi8w3LJbe3gTiKy_
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1bmOl7YInqiI1Y8hIauxLp4hseKa3coCC
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1t9jrCkCNeHnpzj9qWtQ6oX-f7OUVM3Ce
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1tWlRtMSHSx4KP30fuuDVj1RGuZ9LXaKa
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=14D2NFGkWh5-zhBMLVc7NtcQ9N1xQofHj
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1BOQLtDS0H1P5RHPV2HK9aH690Qh1IMy-
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=15ThTYSaTUvBMny2W3pX0PpHF8QaDVicw
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ykz3JmvzcHRaUuaLHOQ7YJcir3c8ZDg-
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1wsesSwJsGsdRjxbdIGA5qfyLJGtiMKVq
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1VhLRrNVzfb1n_3OzphZIbstx2rHcbFb_
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1hQs0t3xSPfQiDeIKMMyUNRDKcEO24elD
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1O6P2R-Xa1rd5B38G1P9MSG5UYleQ7ItW
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1yNt2XDwWvrNOYV2f_oSiyiFFjcavuEdy
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1mjQW-iaDFJMM34sEcnhzGS1vQmq9rJ91
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1xwy7dIwL9FaO8vRzVWHrIZdag5rNBwhC
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ZG0VIi018rd7748kg-xduj0BYEsEAQHK
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1eLwpAJkcnkVzaeTliPYSMU-rVQj44K3z
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1jOOwNaEtMGSg-DLJmmBf0gyOLok8_KO0
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=130cdgkBPbjKjJS8NZh_jxglVcEe9BBG0
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ak24WAlPy-6SmBqQnwJxlEtOXNE1ZaNd
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1oPEnrF5i3hjQKPPBd-qsUj6BURFpmzXg
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=14SixFvZ8kjQxxCYkXifDNQye_QSd2yyy
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ukjwY6ZMxB0NK2MUeUa8xs9auHXk7DaB
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1Pbt_JvS6svPAr6ajBTErKfutpFSnqU9d
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1hfPASHWJhGk4r-BUrlwW-TDjG0A1Lnd2
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1VpQwPpsH88p5PmYaVYgt0xR59zDh3x21
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1Bz6E065aMTKOaYAhe98BtW5ZQnUPUP5w
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1l9Hkw_-avWCYWqUtDoWUsYjnzt7A8C3T
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1UoVu1c543-ikDXaVlHDGW58gwEcgwt2h
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=13R_HpgdHP2jdHe5t_aZ0Ks8MGwh_zRVg
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=10ksQoOEBjFSWGHnKUdHD5ckVdaYYuPSZ
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=13opkLweKXkw24e79hSd_melTyCMl-K_V
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1H4bk0UE-mzYNwKNfvYHQLYV7uAZp9XPM
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1Ld5S503YCRHgFGFCDw7JG7DMujQlXCC-
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1Z-p1e-Qj63DZRzAJ9ZKFPIQTuS23i3Nb
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=14pUCeABJ467U1F6eYzkWEZBhrlcgQZ2p
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1K-y3Y1fSidicVOrtcs6H9PWLEoIfxHEu
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1cwjGg6QWdpQ1R1uFDyauOR0bS9SbqTnP
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1O5i5NkpsfmpWxZb7JDUfmi4U3RI12U9A
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1Dt2DO9VaXGB9xO64rDHA-P0rkY370AXw
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1AwhM04q3XHihZaUdTA6xe4Vg3cwXs7rx
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1VcZ9gDuLuUhGhoUiaQevOSCJOMVFAScu
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1rQ83F1FC88bwLbo19-GjrdfkaYu7NUtk
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=12ijyu8wv3qzTAr_Q9spTXYDQd8YmUZlp
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=13_kVW0uBNaqDLAE3XMExx3kjfzZyBxeD
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=18fc_6vlIEr3rpmTmAmGV271xPLxM75r2
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1FZI4_8CpAqDxgbwqxW1L2Ylygb2g2bz3
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1g-D_Cl1qVlzJtw7FmHbw3CgTvJvZbD62
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=12J1JBJdIdO8dT7qN1PPQ-1Vg2MOBEZ3r
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1CpAvADjsGXEDBUp6UF24DG0vBNueo_73
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1ZuY5DMhV_DHK2cwVUPp3hAoX7OnJchY0
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1eFlUM9Bzjf5OklS6q5PKDFYA4DVvkpzJ
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=127uHUZrPymoSba1pIgDRdxEezR8arD4y
start "c:\Program Files (x86)\Google\Chrome\Application\chrome.exe"  "https://drive.google.com/uc?export=download&id=1MuJ_YrSlgI8Tw6uwW3xGQF-afinKZMKN